apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: "4.10"
  name: performance-addon-operator #need to check
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown
