apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-ts-1-8"
  namespace: "ztp-common"
spec:
  bindingRules:
    common: "true"
    version: TS-1.8
  remediationAction: inform
  sourceFiles:
  # Installing different operators

  # install and configure Sriov (section removed)
  #
  # install and configure MetalLB
    - fileName: custom/metallb/ns.yaml
      policyName: subscriptions
    - fileName: custom/metallb/operatorGroup.yaml
      policyName: subscriptions
    - fileName: custom/metallb/subscription.yaml
      policyName: subscriptions
      spec:
        config:
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master

    - fileName: custom/metallb/instance.yaml
      policyName: config-operators
      spec:
        nodeSelector:
          node-role.kubernetes.io/standard: ""

  # install NMState operator
    - fileName: custom/nmstate/ns.yaml
      policyName: subscriptions
    - fileName: custom/nmstate/operatorGroup.yaml
      policyName: subscriptions
    - fileName: custom/nmstate/subscription.yaml
      policyName: subscriptions
      spec:
        config:
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master

    - fileName: custom/nmstate/instance.yaml
      policyName: "config-operators"
      spec:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: high-throughput
          value: "true"
    # Other networking config
    - fileName: custom/CustomNetwork.yaml
      policyName: config-network
      spec:
        defaultNetwork:
          ovnKubernetesConfig:
            gatewayConfig:
              ipForwarding: "Global"
              routingViaHost: true
          type: OVNKubernetes
#        additionalNetworks:
#          - name: pc-mm-ext
#            namespace: pcc
#            rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "pc-mm-ext", "plugins": [{"type":
#              "macvlan", "master": "bond1", "ipam": {}}] }'
#            type: Raw
#          - name: eric-pc-routing-engine-net0
#            namespace: pcc
#            rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine-net0",
#              "plugins": [ {"type": "macvlan", "master": "bond1", "mode": "private" },{
#              "type": "tuning", "name": "tuning-arp" }] }'
#            type: Raw
#          - name: eric-pc-vpn-gateway-forwarder-common
#            namespace: pcc
#            rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-vpn-gateway-forwarder-common",
#              "plugins": [{"type": "macvlan", "master": "bond1", "mode": "bridge" }, { "type":
#              "tuning", "name": "tuning-arp" }]}'
#            type: Raw
#          - name: eric-pc-routing-engine-net0
#            namespace: pcg
#            rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine-net0", "plugins":
#              [{"type": "macvlan", "master": "bond1", "mode": "private" }, { "type": "tuning",
#              "name": "tuning-arp" }]}'
#            type: Raw
    - fileName: custom/customNamespace.yaml
      policyName: config
      metadata:
        name: pcc
    - fileName: custom/customNamespace.yaml
      policyName: config
      metadata:
        name: pcg
    # - fileName: custom/DedicatedServiceMonitor.yaml
    #   policyName: config
