---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ipmi-secret-geored-workload.yaml
# - ipmi-secret-std-workload.yaml
  - pull-secret-geored-workload.yaml
# - pull-secret-std-workload.yaml
