---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "geored-workload"
  namespace: "geored-workload"
spec:
  baseDomain: "geo2.site"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "img4.16.36-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6WwROwAxk9K5RbDt3b6FEP4WWuRGA4JU5G2j6mq8N2I8l3IMw9A/UF5oeCrKUBJWna3jDK7KpDNKkaKiAhlSU3jAHi5tLQyWmWFijKXYFLOotN9o3vYTktXgcf9B0g6aFqI95qKDxjofj6mcPPfQLPV9Na60PP9B0gBJWF6RUQZy+DYiGeeAueaeTjsM3Y0tvEjMDmWCh57IPMIqsoOpaX+uAMgMu4TxcQvUw8Sh5Al8zhgz+LIg1tAGQAd23jsLnL5K6z+ol0XKq8Qn2ddfOttFCFnVyYs+pcC820MbVp9O7XpaeU8lXaJLpf6jdlRz9VANASdmMLhX6/DpsDqfAmoy++yJQH6Z6fl0OhWuvYpwPFTOm5xWwtbOOiWdA2gT9c5Etl6N/Yl4BaPftCDn9Sk84r+oqtbvYJ79PjVINh/kKtnQwWDNGjyZ7WjaMnf/457ciEOo9YaOEqcnBZSoqkNDOlAB0T4Yq7W/LOIV989M9DrOIMv9uEBomC69ZYm8= root@rhel9rishi"
  clusters:
  - clusterName: "geored-workload"
    extraManifests:
      searchPaths:
        - extra-manifest/
        - custom-manifests/
      # filter:
      #     inclusionDefault: include
      #     exclude:
      #       - 76-enable-crun-master.yaml
      #       - 77-enable-crun-standard.yaml
      #       - 78-enable-crun-ht100gb.yaml
    networkType: "OVNKubernetes"
    clusterLabels:
      common: true
      group-core-standard: ""
      sites : "geored-workload"
      group: "rdu3"
      version: "TS-1.8"
      cloud: BareMetal
      vendor: OpenShift
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    apiVIP: 10.188.23.222 
    ingressVIP: 10.188.23.223 
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 10.188.25.201
        #    holdInstallation: false    
    nodes:
      - hostName: "master0.geored-workload.geo2.site"
        role: "master"
        nodeLabels:
          node-role.kubernetes.io/standard: ""
        bmcAddress: "redfish-virtualmedia://10.188.1.38/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "ipmi-secret"
        bootMACAddress: "1c:98:ec:60:f7:20" #doubt
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0"  
        ignitionConfigOverride: '{"ignition":{"version": "3.2.0"},"storage":{"disks":[{"device":"/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0","wipeTable":true,"partitions":[{"number":1,"sizeMiB":1,"wipePartitionEntry":true},{"number":2,"sizeMiB":127,"wipePartitionEntry":true},{"number":3,"sizeMiB":384,"wipePartitionEntry":true},{"number":4,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:109:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-containers","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:110:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-etcd","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]}],"filesystems":[{"device":"/dev/disk/by-partlabel/var-lib-containers","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-containers"},{"device":"/dev/disk/by-partlabel/var-lib-etcd","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-etcd"}]},"systemd":{"units":[{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-containers.mount"},{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\n\n[Mount]\nWhere=/var/lib/etcd\nWhat=/dev/disk/by-partlabel/var-lib-etcd\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-etcd.mount"}]}}'
        nodeNetwork:
          interfaces:
            - name: eno50
              macAddress: "1c:98:ec:60:f7:20"
            - name: eno49
              macAddress: "1c:98:ec:60:f7:18"
          config:
            interfaces:
              - name: eno50
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: eno49
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: bond0
                type: bond
                state: up
                mtu: 9000
                mac-address: "1c:98:ec:60:f7:20"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                    lacp_rate: slow
                  port:
                    - eno50
                    - eno49
              - name: bond0.23 
                description: node-mgmt geo2.site
                type: vlan
                state: up
                mtu: 9000
                vlan:
                  base-iface: bond0
                  id: 24 
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.188.23.38 
                      prefix-length: 24
                  dhcp: false
                ipv6:
                  enabled: false
                  dhcp: false
                  autoconf: false
            dns-resolver:
              config:
                server:
                - 10.188.25.11
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: bond0.23 
                next-hop-address: 10.188.23.1
                table-id: 254

      - hostName: "master1.geored-workload.geo2.site"
        role: "master"
        nodeLabels:
          node-role.kubernetes.io/standard: ""
        bmcAddress: "redfish-virtualmedia://10.188.1.39/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "ipmi-secret"
        bootMACAddress: "1c:98:ec:60:18:20"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0" 
        ignitionConfigOverride: '{"ignition":{"version": "3.2.0"},"storage":{"disks":[{"device":"/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0","wipeTable":true,"partitions":[{"number":1,"sizeMiB":1,"wipePartitionEntry":true},{"number":2,"sizeMiB":127,"wipePartitionEntry":true},{"number":3,"sizeMiB":384,"wipePartitionEntry":true},{"number":4,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:109:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-containers","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:110:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-etcd","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]}],"filesystems":[{"device":"/dev/disk/by-partlabel/var-lib-containers","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-containers"},{"device":"/dev/disk/by-partlabel/var-lib-etcd","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-etcd"}]},"systemd":{"units":[{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-containers.mount"},{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\n\n[Mount]\nWhere=/var/lib/etcd\nWhat=/dev/disk/by-partlabel/var-lib-etcd\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-etcd.mount"}]}}'
        nodeNetwork:
          interfaces:
            - name: eno50
              macAddress: "1c:98:ec:60:18:20"
            - name: eno49
              macAddress: "1c:98:ec:60:18:18"
          config:
            interfaces:
              - name: eno50
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: eno49
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: bond0
                type: bond
                state: up
                mtu: 9000
                mac-address: "1c:98:ec:60:18:20"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                    lacp_rate: slow
                  port:
                    - eno50
                    - eno49
              - name: bond0.23 
                description: node-mgmt geo2.site
                type: vlan
                state: up
                mtu: 9000
                vlan:
                  base-iface: bond0
                  id: 24
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.188.23.39
                      prefix-length: 24
                  dhcp: false
                ipv6:
                  enabled: false
                  dhcp: false
                  autoconf: false
            dns-resolver:
              config:
                server:
                - 10.188.25.11
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: bond0.23 
                next-hop-address: 10.188.23.1 #doubt
                table-id: 254

      - hostName: "master2.geored-workload.geo2.site"
        role: "master"
        nodeLabels:
          node-role.kubernetes.io/standard: ""
        bmcAddress: "redfish-virtualmedia://10.188.1.40/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "ipmi-secret"
        bootMACAddress: "1c:98:ec:60:d7:c0" 
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0" 
        ignitionConfigOverride: '{"ignition":{"version": "3.2.0"},"storage":{"disks":[{"device":"/dev/disk/by-path/pci-0000:03:00.0-scsi-0:1:0:0","wipeTable":true,"partitions":[{"number":1,"sizeMiB":1,"wipePartitionEntry":true},{"number":2,"sizeMiB":127,"wipePartitionEntry":true},{"number":3,"sizeMiB":384,"wipePartitionEntry":true},{"number":4,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:109:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-containers","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]},{"device":"/dev/disk/by-path/pci-0000:3a:00.0-scsi-0:3:110:0","wipeTable":true,"partitions":[{"number":1,"label":"var-lib-etcd","startMiB":0,"sizeMiB":0,"wipePartitionEntry":true}]}],"filesystems":[{"device":"/dev/disk/by-partlabel/var-lib-containers","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-containers"},{"device":"/dev/disk/by-partlabel/var-lib-etcd","wipeFilesystem":true,"format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/var-lib-etcd"}]},"systemd":{"units":[{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-containers.mount"},{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2detcd.service\n\n[Mount]\nWhere=/var/lib/etcd\nWhat=/dev/disk/by-partlabel/var-lib-etcd\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-etcd.mount"}]}}'
        nodeNetwork:
          interfaces:
            - name: eno50
              macAddress: "1c:98:ec:60:d7:c0" 
            - name: eno49
              macAddress: "1c:98:ec:60:d7:b8"
          config:
            interfaces:
              - name: eno50
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: eno49
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: bond0
                type: bond
                state: up
                mtu: 9000
                mac-address: "1c:98:ec:60:d7:c0"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                    lacp_rate: slow
                  port:
                    - eno50
                    - eno49
              - name: bond0.23 
                description: node-mgmt geo2.site
                type: vlan
                state: up
                mtu: 9000
                vlan:
                  base-iface: bond0
                  id: 24
                ipv4:
                  enabled: true
                  address:
                    - ip: 10.188.23.40
                      prefix-length: 24
                  dhcp: false
                ipv6:
                  enabled: false
                  dhcp: false
                  autoconf: false
            dns-resolver:
              config:
                server:
                - 10.188.25.11
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: bond0.23 
                next-hop-address: 10.188.23.1
                table-id: 254
