apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    infraenv.agent-install.openshift.io/enable-ironic-agent: "true"
    ran.openshift.io/ztp-gitops-generated: '{}'
  labels:
    app.kubernetes.io/instance: siteconfig-workload
  name: geored-workload
  namespace: geored-workload
spec:
  additionalNTPSources:
  - 10.188.25.201
  clusterRef:
    name: geored-workload
    namespace: geored-workload
  cpuArchitecture: x86_64
  ipxeScriptType: DiscoveryImageAlways
  nmStateConfigLabelSelector:
    matchLabels:
      nmstate-label: geored-workload
  proxy:
    httpProxy: http://10.78.90.46:8080
    httpsProxy: http://10.78.90.46:8080
    noProxy: '127.0.0.1,.apps.rhocp.sse.com,.rhocp.sse.com,localhost,.sse.com,172.30.0.0/16,10.188.25.0/24,.geored-workload.geo2.site,.geo2.site,.apps.geored-workload.geo2.site,10.188.19.0/24,10.188.20.0/24,10.188.23.0/24,10.188.26.0/24,10.188.24.0/24,10.128.0.0/14,10.188.1.0/24,10.188.2.0/24,10.188.22.0/24'
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6WwROwAxk9K5RbDt3b6FEP4WWuRGA4JU5G2j6mq8N2I8l3IMw9A/UF5oeCrKUBJWna3jDK7KpDNKkaKiAhlSU3jAHi5tLQyWmWFijKXYFLOotN9o3vYTktXgcf9B0g6aFqI95qKDxjofj6mcPPfQLPV9Na60PP9B0gBJWF6RUQZy+DYiGeeAueaeTjsM3Y0tvEjMDmWCh57IPMIqsoOpaX+uAMgMu4TxcQvUw8Sh5Al8zhgz+LIg1tAGQAd23jsLnL5K6z+ol0XKq8Qn2ddfOttFCFnVyYs+pcC820MbVp9O7XpaeU8lXaJLpf6jdlRz9VANASdmMLhX6/DpsDqfAmoy++yJQH6Z6fl0OhWuvYpwPFTOm5xWwtbOOiWdA2gT9c5Etl6N/Yl4BaPftCDn9Sk84r+oqtbvYJ79PjVINh/kKtnQwWDNGjyZ7WjaMnf/457ciEOo9YaOEqcnBZSoqkNDOlAB0T4Yq7W/LOIV989M9DrOIMv9uEBomC69ZYm8=
    root@rhel9rishi

