---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "9"
    storageclass.kubernetes.io/is-default-class: "true"
  name: ocs-external-storagecluster-ceph-rbd
provisioner: openshift-storage.rbd.csi.ceph.com
reclaimPolicy: Delete
