---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    ran.openshift.io/ztp-deploy-wave: "9"
  name: ocs-external-storagecluster-cephfs
provisioner: openshift-storage.cephfs.csi.ceph.com
reclaimPolicy: Delete
